name = "Killah Potatoes Crate Filler"
prefix = "KPCF"
author = "Cat Harsis"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
[files]
include = [
    "mod.cpp",
    "*.paa"
]

[version]
git_hash = 0 # Disabled

[asc]
enabled = true # Default: false
